services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  metrics-api:
    build:
      context: .
      dockerfile: apps/metrics-api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres  # TODO clean these up to by env variables
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # dev only, remove for prod

  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dashboard

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - dashboard

networks:
  dashboard:
    driver: bridge

volumes:
  grafana-storage:
  pgdata:
